codestudio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('product/', include('product.urls', namespace='product')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('success/', views.success, name='success'),
]

product/urls.py
from django.urls import path, include
from . import views

app_name = 'product'

urlpatterns = [
    path('<slug:title>/', views.product_detail, name='product_detail'),
]

main/models.py
from django.db import models
from django.core import validators
from django.core.exceptions import ValidationError
# Create your models here.


class SeoModel(models.Model):
    seo_title = models.CharField('Title', blank=True, max_length=250)
    seo_description = models.CharField('Description', blank=True, max_length=250)
    seo_keywords = models.CharField('Keywords', blank=True, max_length=250)

    def get_seo_title(self):
        if self.seo_title:
            return self.seo_title
        return ''

    def get_seo_description(self):
        if self.seo_description:
            return self.seo_description
        return ''

    def get_seo_keywords(self):
        if self.seo_keywords:
            return self.seo_keywords
        return ''

    class Meta:
        abstract = True


class Main(SeoModel):
    title = models.CharField(max_length=250, verbose_name='Заголовок')

    class Meta:
        verbose_name = 'Главная страница'
        verbose_name_plural = 'Главная страница'

    def __str__(self):
        return self.title


class SliderImage(models.Model):
    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 2.0
        if filesize > megabyte_limit * 1024 * 1024:
            raise ValidationError("Максимальный размер не больше %sMB" % str(megabyte_limit))

    page = models.ForeignKey(Main, default=None, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='images/slider/',
                               verbose_name='Картинка',
                               validators=[validate_image, validators.FileExtensionValidator(allowed_extensions=('jpg','jpeg',))],
                               error_messages={'invalid_extension': 'Этот формат не поддерживается. Только jpg'})



    class Meta:
        verbose_name = 'Изображения слайдера'
        verbose_name_plural = 'Изображения слайдера'

    def __str__(self):
        return self.page.title

class Text(models.Model):
    page = models.ForeignKey(Main, default=None, on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Текст', blank=True)

    class Meta:
        verbose_name = 'Текст'
        verbose_name_plural = 'Текст'

class Map(models.Model):
    page = models.ForeignKey(Main, default=None, on_delete=models.CASCADE)
    lat = models.FloatField(verbose_name='Широта', blank=True)
    lon = models.FloatField(verbose_name='Долгота', blank=True)

    class Meta:
        verbose_name = 'Кординаты карты'
        verbose_name_plural = 'Кординаты карты'

product/models.py
from django.db import models
from django.urls import reverse
from django.core import validators
from django.core.exceptions import ValidationError
from main.models import SeoModel
# Create your models here.
class Product(SeoModel):

    STATUS_CHOICES = (
        ('hide', 'Скрыть'),
        ('show', 'Показать'),
    )

    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 2.0
        if filesize > megabyte_limit * 1024 * 1024:
            raise ValidationError("Максимальный размер не больше %sMB" % str(megabyte_limit))

    title = models.CharField(max_length=250, verbose_name='Название продукта')
    slug = models.SlugField(max_length=250, unique_for_date='created', verbose_name='Url путь')
    img = models.ImageField(upload_to='images/product/', blank=True,
                            verbose_name='Изображения',
                            validators=[validate_image, validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg',))],
                            error_messages={'invalid_extension': 'Этот формат не поддерживается. Только jpg'})
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обнавлен')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='show', verbose_name='Статус')

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.slug])

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.title

class ListTitle(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='productlisttitle')
    title = models.CharField(max_length=150, verbose_name='Заголовок списка')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Заголовок списка'
        verbose_name_plural = 'Заголовоки списков'

class ListItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.ForeignKey(ListTitle, on_delete=models.CASCADE, verbose_name='Выбрать заголовок', related_name='productlistitem')
    item = models.CharField(max_length=250, verbose_name='Пункт списка')

    def __str__(self):
        return self.item

    class Meta:
        verbose_name = 'Пункт списка'
        verbose_name_plural = 'Пункты списков'

main/forms.py
from django import forms
from .models import *

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    name = forms.CharField(required=True)

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'text-box',
                                                 'placeholder': 'Ваше имя',
                                                 'onfocus': 'blurEvent(this)',
                                                 'onkeyup': 'onChangeEvent(this)',
                                                 'id': 'name'})
        self.fields['from_email'].widget.attrs.update({'class': 'text-box',
                                                       'placeholder': 'Электронная почта',
                                                       'onfocus': 'blurEvent(this)',
                                                       'onkeyup': 'onChangeEvent(this)',
                                                       'id': 'email'})
        self.fields['name'].label = False
        self.fields['from_email'].label = False

product/forms.py
from django import forms
from .models import *

main/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from product.models import Product
# Create your views here.
def index(request):
    main = Main.objects.all()
    img = SliderImage.objects.all()
    text = Text.objects.all()
    map = Map.objects.all()
    products = Product.objects.filter(status='show')

    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            from_email = form.cleaned_data['from_email']
            try:
                send_mail(name, from_email, 'from@who', ['to@who'], fail_silently=False,)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect('success')

    context = {'main': main, 'img': img, 'text': text, 'map': map, 'products': products, 'form': form,}
    return render(request, 'index.html', context)

def success(request):
    return HttpResponse('Сообщение отправленно.')

product/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import *

# Create your views here.

def product_detail(request, title):

    product = get_object_or_404(Product, slug=title, status='show')
    list = ListTitle.objects.filter(product=product)
    item = ListItem.objects.filter(product=product)

    context = {'product': product,
               'list': list,
               'item': item,
               }
    return render(request, 'product.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no, viewport-fit=cover">
    {% block seo %}
	
    {% endblock %}
	<link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Piazzolla:wght@400;900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static "css/swiper-bundle.min.css" %}">
	<link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
{% block content %}
{% endblock %}
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=28ba27e6-8179-45dd-8a90-a542e1883e67" type="text/javascript"></script>
	<script src="{% static "js/swiper-bundle.min.js" %}"></script>
	<script src="{% static "js/main.js" %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load l10n %}

{% block seo %}
{% for main in main %}
	<title>{{ main.get_seo_title }}</title>
    <meta name="description" content="{{ main.get_seo_description }}"/>
    <meta name="keywords" content="{{ main.get_seo_keywords }}"/>
{% endfor %}
{% endblock %}

{% block content %}
<div class="wrapper">
        <div class="content">
            <h1>
                {% for main in main %}
                {% if main.title %}
                {{ main.title }}
                {%  else %}
                Заголовок первого уровня
                {% endif %}
                {% endfor %}
            </h1>
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% if img %}
                    {% for img in img %}
                    {% thumbnail img.images "1280x860" crop="center" as img %}
                    <div class="swiper-slide"><img src="{{ img.url }}" alt="Картинка"></div>
                    {% endthumbnail %}
                    {% endfor %}
                    {% else %}

                    {% endif %}
                </div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>
            <div class="intro-text">
                {% if text %}
                {% for text in text %}
                <p>{{ text.text|linebreaks }}</p>
                {% endfor %}
                {%  else %}
                <p>По мнению учёных, Земля образовалась 4,54 млрд лет назад из межзвёздного газопылевого облака, наряду с Солнцем и другими планетами. Луна сформировалась примерно на 20 млн лет позже в результате столкновения массивного тела с Землёй. Расплавленный наружный слой Земли со временем охлаждался, в результате чего сформировалась твёрдая оболочка — кора.</p>
                <p>Выделение газов и вулканическая активность привели к возникновению первичной атмосферы. Конденсация водяного пара (большинство которого образовалось изо льда комет) привела к возникновению океанов и других водных ресурсов, после чего высокоэнергетическая химия привела к возникновению самовоспроизводящейся молекулы около 4 млрд лет назад.</p>
                <p>Поверхность Земли менялась на протяжении сотен миллионов лет, время от времени объединяясь в суперконтинент, а затем снова распадаясь на отдельные континенты. Примерно 750 млн лет назад начал разделяться самый древний из известных суперконтинентов — Родиния. Через некоторое время континенты снова соединились и сформировали Паннотию, которая разъединилась около 540 млн лет назад.
                <p>Затем образовался последний суперконтинент — Пангея, который разделился около 180 млн лет назад.</p>
                {% endif %}
            </div>
            <div class="products-list">
                <h2>Продукты</h2>
                <ul>
                    {% if products %}
                    {% for product in products %}
                    <li><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></li>
                    {% endfor %}
                    {% else %}
                    no products yet.
                    {% endif %}
                </ul>
            </div>
            {% if map %}
            {% for map in map %}
               <div id="map" data-latitude="{{ map.lat|unlocalize }}" data-longitude="{{ map.lon|unlocalize }}"></div>
            {% endfor %}
            {%  else %}
            <div id="map" data-latitude="55.76" data-longitude="37.64"></div>
            {% endif %}
            <h2>Отправить сообщение</h2>
            <form id="form" method="post">
                {% csrf_token %}
                {{ form }}
<input type="submit" value="Отправить" class="button" onclick="event.preventDefault();onSubmitEvent()">
            </form>
        </div>
    </div>
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block seo %}
	<title>{{ product.get_seo_title }}</title>
    <meta name="description" content="{{ product.get_seo_description }}"/>
    <meta name="keywords" content="{{ product.get_seo_keywords }}"/>
{% endblock %}
{% block content %}
<div class="wrapper">
        <div class="content">
            <a href="{% url 'main:index' %}" class="go-back">На главную</a>
            <h1>{% if product.title %}
                {{ product.title }}
                {%  else %}
                Заголовок первого уровня
                {% endif %}</h1>

            {% if product.img %}
            {% thumbnail product.img "1280x1024" crop="center" as img %}
            <img src="{{ img.url }}" alt="{{ product.title }}" class="product-image">
            {% endthumbnail %}
            {% endif %}

{% if product.productlisttitle.all %}
            <div class="product-info">
{% for list in product.productlisttitle.all %}
                <div class="product-info-item">
                    <h2>{{ list.title }}</h2>
                    <ul>
                       {% for item in list.productlistitem.all %}
                        <li>{{ item.item }}</li>
                        {% endfor %}
                    </ul>
                </div>
{% endfor %}

            </div>
{% endif %}
        </div>
    </div>
{% endblock %}